import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Home Portal",
  description: "Generated by NRR",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
