import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import Sidebar from "@/components/Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Home Portal",
  description: "Generated by NRR",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
